---
title: "R Notebook"
---
# LOADING REQUIREMENTS
## PACKAGES
```{r message=FALSE, warning=FALSE, include=FALSE}
# LIST OF PACKAGES
pkgs = c("tidyverse", "here", "svglite", "ggplot2", "ggrepel",
         "stringr", "BiocManager", "RColorBrewer", "viridis", "magick",
         "nlme", "factoextra", "devtools", "beepr", "remotes",
         "cowplot", "data.table", "strawr", "rtracklayer", "utils",
         "reshape2", "VennDiagram","gridExtra", "eulerr", "scales",
         "InteractionSet", "gplots", "locfdr", "future", "ggbeeswarm", "glossary", "ggalluvial", "UpSetR")
bio_pkgs = c("biomaRt", "DESeq2", "ComplexHeatmap", "apeglm", "vsn",
             "rhdf5", "InteractionSet", "plotgardener", "HiCDCPlus",
             "GenomicInteractions", "LOLA", "AnnotationHub",
             "org.Mm.eg.db", "enrichplot", "DOSE", "clusterProfiler",
             "HiCExperiment", "HiCool", "HiContacts", "HiContactsData", "fourDNData", "DNAZooData",
             "MotifDb", "Biostrings")

# INSTALL PACKAGES
# install.packages(pkgs)
# BiocManager::install(bio_pkgs)

# INSTALL HiC related packages
# remotes::install_github("robinweide/GENOVA")
# devtools::install_github("thomasp85/scico")
# devtools::install_github("psyteachr/introdataviz")

# LOAD PACKAGES
lapply(pkgs, require, character.only = TRUE)
lapply(bio_pkgs, require, character.only = TRUE)
require(GENOVA)
require(scico)
require(introdataviz)
require(igraph)
# CLEANING
rm(pkgs, bio_pkgs)

options(scipen=999)



```
## ENSEMBL
```{r}
# ENSEMBL DATABASE
# v102 is for the latest mm10 version
# ensembl.v102 <- useMart(host = "https://nov2020.archive.ensembl.org",
#                        biomart = "ENSEMBL_MART_ENSEMBL",
#                        dataset = "mmusculus_gene_ensembl")
```
## COLOR PALETTE
```{r}
palette_1 = list(red = "#E9002D",
                 amber = "#FFAA00",
                 green = "#00B000")
palette_2 = list(red = "#FF1F5B",
                 green = "#00CD6C",
                 blue = "#009ADE",
                 purple = "#AF58BA",
                 yellow = "#FFC61E",
                 orange = "#F28522",
                 grey = "#A0B1BA",
                 brown = "#A6761D")
palette_3 = list(grey1 = "#a0b1ba",
                 grey2 = "#c5d0d5",
                 grey3 = "#eceff1")

colorListLoop <-  c(palette_3[["grey3"]], palette_3[["grey2"]], palette_3[["grey1"]],
                     "#C5E1EF", "#6CB0D6", "#226E9C",
                     "#06592A", 
                     "#FED976", "#FD8D3C", "#E31A1C")
colorListPromoter <- c(palette_3[["grey3"]],"#E88587", "#E31A1C")
colorListEnhancer <- c(palette_3[["grey3"]],"#87AFC7", "#226E9C")
colorListStructure <- c(palette_3[["grey3"]], palette_3[["grey2"]], palette_3[["grey1"]])
```

## DIR LIST
```{r}
loopDir <- "/Volumes/UKJIN_SSD/data/loop_Tjian"
figDir <- "/Volumes/UKJIN_SSD/figure/loop_Tjian"
refDir <- here("../reference")

dir.create(figDir, showWarnings = FALSE)
```

## FIGURE PARAMETERS
```{r}
library(colorspace)

fontType <- "Helvetica"

fontSizeL <- 10 # pt
fontSizeM <- 8
fontSizeS <- 6

lineThick <- 0.75 # pt
lineMedium <- 0.5
lineThin <- 0.25

panelUnit <- 30 # mm
panelMargin <- 1.5

mmToInch <- 0.03937007874
mmToLineUnit <- 1/2.13
mmToLinePlotgarden <- 1/0.75
ptToMM <- 1/2.845


strong_red <- "#CB333A"
strong_blue <- "#4851A0"
weak_red <- lighten(strong_red, amount = 0.4)   # FF7D81
weak_blue <- lighten(strong_blue, amount = 0.4) # 8A91DD
no_grey <- "#A8A8A8"

strong_teel <- "#0892A5"
strong_green <- "#23CE6B" # A485
strong_darkgreen <- "#054A29"
strong_yellow <- "#FFBA49"
strong_orange <- "#F18F01" # dTAG
strong_lightpurple <- "#BD93D8"
strong_purple <- "#9E33CB" # Epi

panelSize <- function(num, unit = panelUnit, margin = panelMargin){
  return(num*unit - 2*margin)
}

```

## FUNCTIONS
```{r}
importBedpe = function(bedpe){
  a1 = makeGRangesFromDataFrame(data.frame(
    chr = bedpe$V1,
    start = bedpe$V2 +1,
    end = bedpe$V3))
  a2 = makeGRangesFromDataFrame(data.frame(
    chr = bedpe$V4,
    start = bedpe$V5 +1,
    end = bedpe$V6))
  GInteractions(a1, a2)
}

get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
label_kb_mb <- function(x) {
  ifelse(x >= 1000000, paste0(x / 1000000, "Mb"), paste0(x / 1000, "kb"))
}

importPeak = function(fileName){
  df = fread(fileName)
  gr = makeGRangesFromDataFrame(data.frame(
    chr = df$V1, start = df$V2, end = df$V3
  ))
}
```

# Postprocessing
```{r}
loops <- fread(here(loopDir, "TjianChromo_union_allRes.bedpe"))
colnames(loops) <- c("chrom1", "start1", "end1", "chrom2", "start2", "end2")
loops <- loops %>% dplyr::mutate(bin = end1 - start1,
                                 size = start2 - start1,
                                 id = paste(chrom1, start1, end1, chrom2, start2, end2, sep = "_"))


temp <- fread(here(loopDir, "TjianChromo_union_allRes_cohesin.bedpe"))
colnames(temp) <- c("chrom1", "start1", "end1", "chrom2", "start2", "end2")
temp <- temp %>% dplyr::mutate(bin = end1 - start1,
                               size = start2 - start1,
                               id = paste(chrom1, start1, end1, chrom2, start2, end2, sep = "_"))

loops <- loops %>% dplyr::mutate(cohesin = ifelse(id %in% temp$id, TRUE, FALSE))

```

# Splitting loops into different resolutions for loop score calculation
```{r}
loops <- fread(here(loopDir, "TjianChromo_union_allRes.bedpe")) %>%
  dplyr::mutate(size = V3-V2)

saveResBedpe <- function(loops, res, loopDir, name){
  temp <- loops %>% dplyr::filter(size == res) %>% dplyr::select(seq(1, 6))
  cols_to_check <- c(2, 3, 5, 6)
  
  # This line will stop the function if any value in ANY of the specified
  # columns is NOT a multiple of 'res'.
  stopifnot(
    "Values in one or more specified columns (2, 3, 5, 6) are not multiples of res" =
      all(as.matrix(temp[, ..cols_to_check]) %% res == 0)
  )
  
  fwrite(temp, here(loopDir, paste0(name, "_", res, "bp.bedpe")), sep = "\t", col.names = FALSE)
} 

saveResBedpe(loops, 400, loopDir, "TjianChromo_union")
saveResBedpe(loops, 600, loopDir, "TjianChromo_union")
saveResBedpe(loops, 800, loopDir, "TjianChromo_union")
saveResBedpe(loops, 1000, loopDir, "TjianChromo_union")
saveResBedpe(loops, 2000, loopDir, "TjianChromo_union")
saveResBedpe(loops, 4000, loopDir, "TjianChromo_union")
saveResBedpe(loops, 10000, loopDir, "TjianChromo_union")
saveResBedpe(loops, 20000, loopDir, "TjianChromo_union")


```

# ChromHMM based annotation
### Functions
```{r}
createLoopAnnotation <- function(bedpe.loop.anno, name, figDir){
  temp = bedpe.loop.anno %>%
    dplyr::mutate(sample = name)
  
  # num = nrow(temp)
  # p7 = ggplot(temp, aes(x = sample, fill = Anno2)) +
  #   geom_bar(color = "black") +
  #   theme_bw() +
  #   labs(title = paste0(num, " loops"),
  #        x = "", y = "Counts") +
  #   scale_y_continuous(labels = comma_format()) +
  #   theme(plot.title = element_text(hjust = 0.5),
  #         aspect.ratio = 5,
  #         legend.position = "right",
  #         legend.direction  = "vertical")
  # +
  # scale_fill_manual(values = colorList)
  
  pie_df <- temp %>%
    as_tibble() %>%                          # if temp was a list, this will error early
    group_by(Anno2) %>%
    summarise(n = n(), .groups = "drop") %>%
    mutate(label = paste0(Anno2, " (", n, ")"))
  
  
  p7 <- ggplot(pie_df, aes(x = "", y = n, fill = Anno2)) +
    geom_col(color = "black", width = 1) +
    coord_polar(theta = "y") +
    geom_text(aes(label = label),
              position = position_stack(vjust = 0.5),
              size = 3) +
    theme_void() +   theme(legend.position = "none")
  
  width = 3
  height = 3
  svglite(here(figDir,
               paste0("loopClassify_", name, ".svg")),
          width = width, height = height)
  plot(p7)
  invisible(dev.off())
  png(here(figDir,
           paste0("loopClassify_", name, ".png")),
      width = width, height = height, res = 600, units = "in")
  plot(p7)
  invisible(dev.off())

  
  }

```

### Group ChromHMM + RAD21 peaks
### Annotate anchors
```{r}
loop <- as_tibble(fread(here(loopDir, "TjianChromo_union_allRes.bedpe")))

anchor1.tb <- as_tibble(loop) %>% dplyr::select(V1, V2, V3)
colnames(anchor1.tb) <- c("chr", "start", "end")
anchor2.tb <- as_tibble(loop) %>% dplyr::select(V4, V5, V6)
colnames(anchor2.tb) <- c("chr", "start", "end")
anchor.tb <- bind_rows(anchor1.tb, anchor2.tb) %>% 
  distinct()

anchor <- makeGRangesFromDataFrame(data.frame(anchor.tb))
chromHMM <- fread(here(refDir, "chromHMM_fullstack", "mm10_100_segments_segments_grouped_ChIP.bed"))
colnames(chromHMM) <- c("chr", "start", "end", "state")
chromHMM <- makeGRangesFromDataFrame(data.frame(chromHMM), keep.extra.columns = TRUE)

hits <- findOverlaps(anchor, chromHMM, minoverlap = 2)
ov <- as.data.frame(hits)
collapsed <- ov %>%
  group_by(queryHits) %>%
  summarize(annot = paste(unique(mcols(chromHMM)$state[subjectHits]), collapse=";"))

anchor.tb$annot <- NA_character_
anchor.tb$annot[collapsed$queryHits] <- collapsed$annot

anchor.tb <- anchor.tb %>% dplyr::mutate(annotSingle = case_when(
  str_detect(annot, regex("SP",     ignore_case = TRUE)) ~ "SP",
  str_detect(annot, regex("SE",     ignore_case = TRUE)) ~ "SE",
  str_detect(annot, regex("S",     ignore_case = TRUE)) ~ "S",
  str_detect(annot, regex("P",     ignore_case = TRUE)) ~ "P",
  str_detect(annot, regex("E",     ignore_case = TRUE)) ~ "E",
  TRUE ~ "X",
))

fwrite(anchor.tb, here(loopDir, "TjianChromo_union_allRes_anchor.bed"), sep = "\t", col.names = FALSE)

# Visualize anchor classification
colorList <- rev(c(colorListPromoter[3], colorListEnhancer[3], colorListPromoter[2], colorListEnhancer[2], colorListStructure[3], colorListStructure[1]))
anchor.tb$annotSingle <- factor(anchor.tb$annotSingle, rev(c("P", "E", "SP", "SE", "S", "X")))
temp <- anchor.tb %>% dplyr::mutate(name = "anchor")
num <- nrow(temp)
p <- ggplot(temp, aes(x = name, fill = annotSingle)) +
  geom_bar(color = "black") +
  theme_bw() +
  labs(title = paste0(num, " anchors"),
       x = "", y = "Counts") +
  scale_y_continuous(labels = comma_format()) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 5,
        legend.position = "right",
        legend.direction  = "vertical") +
    scale_fill_manual(values = colorList)

svglite(here(figDir, "anchorClassify_TjianChromo_union_allRes_chromHMMRAD21.svg"), width = 3, height = 5)
print(p)
dev.off()
```
### Annotate loops
```{r}
anchor.tb <- fread(here(loopDir, "TjianChromo_union_allRes_anchor.bed")) %>%
  dplyr::mutate(anchor_id = paste(V1, V2, V3, sep = "_")) %>%
  rename(annot = V5)

consensus.loop.anno.tb <- fread(here(loopDir, "TjianChromo_union_allRes.bedpe"))
colnames(consensus.loop.anno.tb) <- c("chrom1", "start1", "end1", "chrom2", "start2", "end2")

consensus.loop.anno.tb <- consensus.loop.anno.tb %>%
  dplyr::mutate(anchor_id_1 = paste(chrom1, start1, end1, sep = "_"),
                anchor_id_2 = paste(chrom2, start2, end2, sep = "_"))


consensus.loop.anno.tb <- consensus.loop.anno.tb %>%
  left_join(
    anchor.tb %>% select(anchor_id, annot),
    by = c("anchor_id_1" = "anchor_id")
  ) %>%
  rename(A1 = annot) %>%
  left_join(
    anchor.tb %>% select(anchor_id, annot),
    by = c("anchor_id_2" = "anchor_id")
  ) %>%
  rename(A2 = annot) %>%
  dplyr::mutate(A1_simple = recode(A1,
                                   "SE" = "S",
                                   "SP" = "S"),
                A2_simple = recode(
                  A2,
                  "SE" = "S",
                  "SP" = "S"
                ))

order_lvls <- c("P","E","SP","SE","S","X")
rank_map   <- setNames(seq_along(order_lvls), order_lvls)
consensus.loop.anno.tb <- consensus.loop.anno.tb %>%
  mutate(
    r1 = rank_map[A1],           # map A1 → 1..6
    r2 = rank_map[A2],           # map A2 → 1..6
    first  = if_else(r1 <= r2, A1, A2),
    second = if_else(r1 <= r2, A2, A1),
    Anno  = paste(first, second, sep = "-")
  ) %>%
  select(-r1, -r2, -first, -second)


order_lvls <- c("P","E","S","X")
rank_map   <- setNames(seq_along(order_lvls), order_lvls)
consensus.loop.anno.tb <- consensus.loop.anno.tb %>%
  mutate(
    r1 = rank_map[A1_simple],           # map A1 → 1..6
    r2 = rank_map[A2_simple],           # map A2 → 1..6
    first  = if_else(r1 <= r2, A1_simple, A2_simple),
    second = if_else(r1 <= r2, A2_simple, A1_simple),
    Anno_simple  = paste(first, second, sep = "-")
  ) %>%
  select(-r1, -r2, -first, -second)


name <- "TjianChromo_union_allRes"
fwrite(consensus.loop.anno.tb, here(loopDir, paste0(name, "_annotated.tsv")), 
       sep = "\t", col.names = TRUE)

temp <- consensus.loop.anno.tb %>% rename(Anno2 = Anno_simple)
temp$Anno2 <- factor(temp$Anno2, levels = rev(c("P-P", "P-E", "E-E",
                                                "P-S", "E-S",
                                                "P-X", "E-X", "S-X",
                                                "X-X",
                                                "S-S")))
createLoopAnnotation(temp, paste0(name, "_annotated_simple"), figDir)


temp <- consensus.loop.anno.tb %>% rename(Anno2 = Anno)
temp$Anno2 <- factor(temp$Anno2, levels = rev(c("P-P", "P-E", "E-E",
                                                "P-SP", "P-SE", "P-S", "E-SP", "E-SE", "E-S",
                                                "P-X", "E-X", "SP-X", "SE-X", "S-X",
                                                "X-X",
                                                "SP-SP", "SP-SE", "SP-S", "SE-SE", "SE-S", "S-S")))

createLoopAnnotation(temp, paste0(name, "_annotated_complex"), figDir)

```

